# Generated by Django 4.1.7 on 2023-04-29 19:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Request",
            new_name="RequestMoney",
        ),
        migrations.RenameModel(
            old_name="Transfer",
            new_name="TransferMoney",
        ),
    ]
